name: update-contracts
on:
  push:
  pull_request_target:
  workflow_dispatch:
  schedule:
    - cron: '0 15-17,23 * * 1,3,5'
    # run once a day a little late on non contract days in case kev does something weird
    - cron: '0 17 * * 0,2,4,6'
jobs:
  update:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: periodicals
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Pip stuff
        run: |
          pip install -r requirements.txt
      - name: Update events
        run: |
          python ./updatePeriodicals.py contracts
        env:
          EI_USERID: ${{ secrets.EI_USERID }}
      - name: Commit, push changes, and possibly trigger new build
        run: |
          git config user.name 'github-actions'
          git config user.email 'actions@github.com'
          git add data/contracts.json
          git diff --cached --quiet || {
            git commit -m 'contracts: update data/contracts.json (from GitHub Actions)'
            git push
            # Use a separate personal access token since the token included doesn't seem to trigger
            # anything, although the response (HTTP 204) looks all right.
            curl -fsS -D- \
              -X POST \
              -H 'Authorization: Bearer ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}' \
              -H 'Accept: application/vnd.github.v3+json' \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows/build-eicoops.yml/dispatches \
              -d '{"ref": "'${GITHUB_REF##*/}'"}'
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
